### ISSUE TITLE
Replace `COALTON-LIBRARY:LIST` with `CL:LIST`

### ISSUE THREAD

**Issue by eliaslfox** [coalton-lang/coalton#144]
Replace the list definition in the standard library with a primitive type that is a standard lisp list under the hood. This should improve performance and allow using standard lisp functions for lisp manipulation.

**Comment by stylewarning** [comment]
One possible bit of confusion that may arise is that if we implement #145, then at run-time `cl:nil` will be recognized ambiguously as both a Coalton Boolean and a Coalton List. This isn't necessarily wrong, it just makes type discrimination in Common Lisp impossible. Coalton, however, should have no issue, since that's only needed at codegen time, and not before.
