### ISSUE TITLE
Missing packages when running (asdf:test-system :coalton)

### ISSUE THREAD

**Issue by HM0880** [coalton-lang/coalton#190]
I needed to install `(ql:quickload :fiasco)` and `(ql:quickload :json-streams)` for `(asdf:test-system :coalton)` to finish.

`fiasco` is already in the .asd file. The .asd file has `#:coalton-json/tests`, but no `json-streams`.  (I assume that the .asd file controls test-system dependencies.)

Let me know what I can do to help fix the missing packages.

**Comment by stylewarning** [comment]
The dependency is properly specified in [coalton-json](https://github.com/coalton-lang/coalton/blob/main/examples/coalton-json/coalton-json.asd#L6).

The problem is that `asdf:test-system` won't download dependencies for you. You need to `(ql:quickload :coalton/tests)` to download all the needed dependencies, then you can run `asdf:test-system`.
