### ISSUE TITLE
Polymorphic integer operators

### ISSUE THREAD

**Issue by gefjon** [coalton-lang/coalton#399]
How do we extend e.g. `even?` and `odd?` to support types other than `Integer`?

**Comment by stylewarning** [comment]
Random thoughts:

I've long wondered this about the organization of Haskell code, and even Lisp code. Namely: What makes for reasonable polymorphic functions (and in the Haskell case, type classes)? On one hand you don't want to have hundreds of tiny, mostly inconsequential type classes (like `Xable` implementing `X`). On the other hand, over the long term, you also don't seem to want giant type classes with 10 methods that don't really correspond to any reasonable definition of the type being constrained. 

There's also a question of definition. While a bit contrived, what does "even" mean? Is any monoidal structure which can be written as a product of pairs of non-identity elements even? Is `4.0` even? Is a binary string with a 0 bit at index 0 even? Is any quantity of type `:t` considered even iff it is `Into :t Integer` and the resulting integer is even?

It may even be valid to say `even?` just doesn't make sense to be polymorphic because no choice will make anybody happy. 

This is seemingly only problematic for "open world" code like a standard library. 

Sorry, this post is just food for thought, but actually proposing an answer.

**Comment by gefjon** [comment]
Within the standard library, I want `even?` to be applicable to all of `(U|I)(8|16|32|64|Fix)` and `Integer`. If we get `U1` or `Bit`, I would want it on them. If we get `BitVector`, I could be convinced either way as to whether it should support `even?`. Outside of those, I want applying `even?` to any standard type to be a compiler error. I notably want `even?` to exclude floats and rationals.

Given that desire, I see two paths forward:

1. Define `even?` in terms of `Bits`, so that given `(Bits :type)`, an instance of `:type` is even iff its zeroth bit is even. This one feels intuitive and pretty to me, but as I like to joke, I'm a computer scientist first and a mathematician sixth. @eliaslfox seemed resistant to that formulation, and I can see why it would feel unnatural to someone with a different background than mine. It also may not generalize well to other integer operators; if we want to offer e.g. `gcd` and `lcm`, it would be unwieldy to try to define them in terms of `Bits`.
2. Define `Integral` as a subclass of `Num`. This is what Haskell does, and it puts the various integer division operators like `quot` (our `floor/`), `mod` and `rem` on that class. `even?` is then `(zero? (rem n 2))`. I don't want to fall into a trap where we blindly reimplement Haskell's standard library, since there are many cases where I think Haskell made the wrong choice, but in this case it seems reasonable.

**Comment by stylewarning** [comment]
@gefjon If we go with the first option, what about if the object is representable as an `Integer` instead of `Bits`? That way all standard library types would "just" be an identity function to "convert" to `Integer`, and evenness checking will be cheap.

**Comment by gefjon** [comment]
I don't love this because it introduces needless runtime dispatch -- `even?` will have to include a hopefully-dead branch to check if the `Integer` representation is a fixnum or a bignum. I doubt that matters much for performance, but it feels sorta ugly to me. Also, user types may have to actually cons bignums, which seems undesirable.

I'm convincing myself of `Integral` more and more; it would be nice to be able to `floor/`, `mod` and `rem` on fixed-width integer types.

**Comment by eliaslfox** [comment]
This has been solved
