### ISSUE TITLE
note: deleting unreachable code

### ISSUE THREAD

**Issue by eliaslfox** [coalton-lang/coalton#880]
This needs to stop

**Comment by gefjon** [comment]
You could `#+sbcl (declare (sb-ext:muffle-conditions sb-ext:code-deletion-note))` in an `:around-compile` ASDF hook.

**Comment by colescott** [comment]
These warnings are caused by SBCL correctly identifying that some match expressions are exhaustive and do not need the fallback case emitted [here](https://github.com/coalton-lang/coalton/blob/main/src/codegen/codegen-expression.lisp#L148). While we do omit this branch when matching on booleans (a common lisp `if` is used) or when a catch-all wildcard is included, this is something we unfortunately cannot remove when running in development mode since types can always be redefined to include more constructors. 

One way we can go about minimizing these warnings is to special case on exhaustive matches on known frozen types (all standard library types in development or all types in production mode) and skip emitting the fallback case. This will cut down on most of the warnings but will not help with user code where we cannot guarantee that types will be frozen. We can muffle any remaining warnings with the declaration mentioned by @gefjon in a local block around the match.

@eliaslfox Do you have any thoughts on this approach?
